### ISSUE TITLE
Training Data Missing?

### ISSUE THREAD

**Issue by linjlpp** [Lorraine333/ACL_CKBC#2]
Hi,

In each train.py of different model, there is a line: 

"(words, We) = getWordmap('../commonsendata/embeddings/tuples/embeddings.skip.newtask.en.d'+str(sys.argv[1])+'.m1.w5.s0.it20.txt')"

I don't understand where is the file '../commonsendata/embeddings/tuples/embeddings.skip.newtask.en.d'+str(sys.argv[1])+'.m1.w5.s0.it20.txt'?

Thanks a lot,
-A Python/Github/DNN/... Newcomer

**Comment by Lorraine333** [comment]
Hi, 

Sorry for the late reply. 

You should change that name as ~/embeddings/embedding.txt if you are downloading the pre trained embedding data from http://ttic.uchicago.edu/~kgimpel/commonsense.html and put it into a directory under the same working directory.  

Sorry for the confusion and we updated the code already. 

Thanks a lot, 
Xiang
